name: Build Container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | podman login -u ${{ github.actor }} --password-stdin ghcr.io
          podman build -t ghcr.io/${{ github.repository_owner }}/emacs-gui:latest .
          podman push ghcr.io/${{ github.repository_owner }}/emacs-gui:latest
